[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
ethabi = { version = "18.0", default-features = false }
{%- unless risc0_std %}
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
{%- endunless %}
risc0-zkvm = { {{ risc0_zkvm }}, default-features = false{{ risc0_feature_std }} }

[profile.release]
lto = true
opt-level = 3
