name: solc install
description: Install solidity compiler
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      run: |
        echo "SOLC_ARCH=linux-amd64" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'macOS'
      run: |
        echo "SOLC_ARCH=macosx-amd64" >> $GITHUB_ENV
      shell: bash

    - env:
        SOLC_URL: https://binaries.soliditylang.org
        SOLC_VERSION: v0.8.19+commit.7dd6d404
      run: |
        curl --output solc "$SOLC_URL/$SOLC_ARCH/solc-$SOLC_ARCH-$SOLC_VERSION"
        chmod +x solc
        mkdir -p $HOME/.local/bin
        mv -f ./solc $HOME/.local/bin/solc
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
