[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies.risc0-build]
git = "https://github.com/risc0/risc0.git"
rev = "4abdbb36ca26397c4b6d448b1fcf02539e80ae21"

[dependencies.risc0-zkvm]
git = "https://github.com/risc0/risc0.git"
rev = "4abdbb36ca26397c4b6d448b1fcf02539e80ae21"

[dependencies]
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"

[package.metadata.risc0]
methods = ["guest"]